# Generated by Django 2.0.8 on 2018-09-05 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20180824_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='desconto',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
