# Generated by Django 2.0.8 on 2018-09-20 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_auto_20180910_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscricao',
            options={'ordering': ('usuario__nome_completo',), 'verbose_name': 'inscrição', 'verbose_name_plural': 'inscrições'},
        ),
        migrations.AlterModelOptions(
            name='tipoinscricao',
            options={'ordering': ('nome',), 'verbose_name': 'tipo de inscrição', 'verbose_name_plural': 'tipos de inscrição'},
        ),
    ]
