# Generated by Django 2.0.10 on 2019-01-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_auto_20180920_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='certificado',
        ),
    ]
