# Generated by Django 2.0.8 on 2018-08-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('instituicao', models.CharField(max_length=255, verbose_name='instituição')),
                ('curso', models.CharField(max_length=255, verbose_name='curso')),
                ('ativo', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False, verbose_name='administrador')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
