# Generated by Django 2.0.8 on 2018-08-09 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Definicoes',
            fields=[
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='def_minicursos', serialize=False, to='eventos.Evento')),
                ('maximo', models.IntegerField(default=1, verbose_name='máximo de inscrições por pessoa')),
            ],
            options={
                'verbose_name': 'definição de minicurso',
                'verbose_name_plural': 'definições de minicurso',
            },
        ),
        migrations.CreateModel(
            name='Minicurso',
            fields=[
                ('atividade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventos.Atividade')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('pre_requisitos', models.TextField(blank=True, null=True, verbose_name='pré-requisitos')),
                ('vagas', models.PositiveIntegerField(default=0)),
                ('inscritos', models.PositiveIntegerField(default=0, verbose_name='número de inscritos')),
                ('vagas_reserva', models.PositiveIntegerField(default=0)),
                ('inscritos_reserva', models.PositiveIntegerField(default=0, verbose_name='número de inscritos na reserva')),
            ],
            options={
                'ordering': ('nome',),
            },
            bases=('eventos.atividade',),
        ),
        migrations.CreateModel(
            name='Ministrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/ministrante')),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='minicurso',
            name='ministrante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minicursos.Ministrante'),
        ),
    ]
