# Generated by Django 2.0.10 on 2019-01-27 18:00

import certificados.models
from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0007_remove_inscricao_certificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=300)),
                ('atividade', models.CharField(max_length=300)),
                ('tipo_atividade', models.CharField(blank=True, max_length=30, null=True)),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='eventos.Inscricao')),
            ],
        ),
        migrations.CreateModel(
            name='ModeloCertificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('paisagem', models.BooleanField(default=True)),
                ('caixa_largura', models.FloatField()),
                ('caixa_altura', models.FloatField()),
                ('caixa_esquerda', models.FloatField()),
                ('caixa_topo', models.FloatField()),
                ('tamanho_fonte', models.IntegerField(default=18)),
                ('conteudo', models.TextField()),
                ('imagem', models.ImageField(blank=True, upload_to=certificados.models.upload_imagem)),
            ],
            options={
                'verbose_name': 'Modelo de Certificado',
                'verbose_name_plural': 'Modelos de Certificado',
            },
        ),
        migrations.AddField(
            model_name='certificado',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='certificados.ModeloCertificado'),
        ),
        migrations.AlterUniqueTogether(
            name='certificado',
            unique_together={('atividade', 'tipo_atividade', 'inscricao')},
        ),
    ]
