# Generated by Django 2.0.8 on 2018-09-01 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0003_auto_20180824_1831'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='trabalhos')),
                ('situacao', models.IntegerField(choices=[(0, 'Pendente'), (1, 'Aprovado'), (2, 'Reprovado')], default=0, editable=False, verbose_name='situação')),
                ('inscricoes', models.ManyToManyField(blank=True, related_name='oficinas', to='eventos.Inscricao')),
                ('ministrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficinas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
