# Generated by Django 2.0.8 on 2018-09-20 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oficinas', '0002_auto_20180920_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesaRedonda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='mesas_redondas')),
                ('situacao', models.IntegerField(choices=[(0, 'Pendente'), (1, 'Aprovado'), (2, 'Reprovado')], default=0, editable=False, verbose_name='situação')),
                ('ministrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesasredondas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mesa-redonda',
                'verbose_name_plural': 'mesas-redondas',
                'ordering': ('nome',),
            },
        ),
        migrations.AlterField(
            model_name='oficina',
            name='arquivo',
            field=models.FileField(upload_to='oficinas'),
        ),
    ]
