# Generated by Django 2.0.8 on 2018-11-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficinas', '0004_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='vagas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='inscricoes',
            field=models.ManyToManyField(blank=True, editable=False, related_name='oficinas', to='eventos.Inscricao'),
        ),
    ]
