# Generated by Django 2.0.8 on 2018-11-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_auto_20180920_1904'),
        ('oficinas', '0005_auto_20181105_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesaredonda',
            name='inscricoes',
            field=models.ManyToManyField(blank=True, editable=False, related_name='mesasredondas', to='eventos.Inscricao'),
        ),
    ]
