# Generated by Django 2.0.8 on 2018-08-17 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areatema',
            name='avaliadores',
        ),
    ]
