# Generated by Django 2.0.8 on 2018-08-17 00:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trabalhos', '0002_remove_areatema_avaliadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='areatema',
            name='avaliadores',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
