# Generated by Django 2.0.8 on 2018-09-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0002_auto_20180920_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalho',
            name='situacao',
            field=models.IntegerField(choices=[(0, 'Pendente'), (1, 'Aprovado'), (2, 'Reprovado'), (3, 'Necessita correção'), (4, 'Reenviado')], default=0, editable=False, verbose_name='situação'),
        ),
    ]
