# Generated by Django 2.0.8 on 2018-10-11 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trabalhos', '0004_trabalho_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='avaliador',
            field=models.ForeignKey(editable=False, blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabalhos', to=settings.AUTH_USER_MODEL),
        ),
    ]
