# Generated by Django 2.0.8 on 2018-10-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0005_trabalho_avaliador'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='carta_aceite',
            field=models.FileField(null=True, upload_to='cartas-de-aceite', verbose_name='Carta de aceite'),
        ),
    ]
