# Generated by Django 2.0.8 on 2018-10-22 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0006_trabalho_carta_aceite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalho',
            name='avaliador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabalhos', to=settings.AUTH_USER_MODEL),
        ),
    ]
